package com.josephusdanieljmartfa.model;

public enum ProductCategory {

    BOOK, KITCHEN, ELECTRONIC, FASHION, GAMING, GADGET, MOTHERCARE, HEALTHCARE,
    FURNITURE, JEWELRY, TOYS, FNB, STATIONERY, SPORTS, AUTOMOTIVE, PETCARE, ART_CRAFT,
    CARPENTRY, MISCELLANEOUS, PROPERTY, TRAVEL, WEDDING;
}
